# Generated by Django 5.1.5 on 2025-02-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='intro',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='review',
            new_name='text',
        ),
    ]
